// ignore_for_file: public_member_api_docs
// This file mirrors the structure generated by `flutterfire configure`.
// Replace placeholder values with the real options per flavor after running
// the CLI against each Firebase project.

import 'package:app/config/app_flavor.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/foundation.dart';

class DefaultFirebaseOptions {
  static FirebaseOptions currentPlatform(AppFlavor flavor) {
    if (kIsWeb) {
      return web(flavor);
    }

    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android(flavor);
      case TargetPlatform.iOS:
        return ios(flavor);
      case TargetPlatform.macOS:
        return macos(flavor);
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions android(AppFlavor flavor) {
    switch (flavor) {
      case AppFlavor.dev:
        return _androidDev;
      case AppFlavor.prod:
        return _androidProd;
    }
  }

  static FirebaseOptions ios(AppFlavor flavor) {
    switch (flavor) {
      case AppFlavor.dev:
        return _iosDev;
      case AppFlavor.prod:
        return _iosProd;
    }
  }

  static FirebaseOptions macos(AppFlavor flavor) => ios(flavor);

  static FirebaseOptions web(AppFlavor flavor) {
    switch (flavor) {
      case AppFlavor.dev:
        return _webDev;
      case AppFlavor.prod:
        return _webProd;
    }
  }

  static const FirebaseOptions _androidDev = FirebaseOptions(
    apiKey: 'AIzaSyBu8WjvhcE1TB1YjV3P1Z4XL_tqcP9k3lE',
    appId: '1:1036900576518:android:1fcefdec445914cf9c0287',
    messagingSenderId: '1036900576518',
    projectId: 'hanko-field',
    storageBucket: 'hanko-field.firebasestorage.app',
  );

  static const FirebaseOptions _androidProd = FirebaseOptions(
    apiKey: 'AIzaSyBu8WjvhcE1TB1YjV3P1Z4XL_tqcP9k3lE',
    appId: '1:1036900576518:android:1fcefdec445914cf9c0287',
    messagingSenderId: '1036900576518',
    projectId: 'hanko-field',
    storageBucket: 'hanko-field-prod.firebasestorage.app',
  );

  static const FirebaseOptions _iosDev = FirebaseOptions(
    apiKey: 'AIzaSyAcRdlxHxhOEj2l_Vj6gxYOkrwrHbg32NI',
    appId: '1:1036900576518:ios:f24ee9a689b943f09c0287',
    messagingSenderId: '1036900576518',
    projectId: 'hanko-field',
    storageBucket: 'hanko-field.firebasestorage.app',
    iosBundleId: 'org.finitefield.hanko',
  );

  static const FirebaseOptions _iosProd = FirebaseOptions(
    apiKey: 'AIzaSyAcRdlxHxhOEj2l_Vj6gxYOkrwrHbg32NI',
    appId: '1:1036900576518:ios:f24ee9a689b943f09c0287',
    messagingSenderId: '1036900576518',
    projectId: 'hanko-field',
    storageBucket: 'hanko-field-prod.firebasestorage.app',
    iosBundleId: 'org.finitefield.hanko',
  );

  static const FirebaseOptions _webDev = FirebaseOptions(
    apiKey: 'AIzaSyAKYkwDTD1EGYgreG_hCmyWRXdG7GgFxMc',
    appId: '1:1036900576518:web:72b66c4c58bd8b4e9c0287',
    messagingSenderId: '1036900576518',
    projectId: 'hanko-field',
    authDomain: 'hanko-field.firebaseapp.com',
    storageBucket: 'hanko-field.firebasestorage.app',
    measurementId: 'G-V2TDW9Z84Y',
  );

  static const FirebaseOptions _webProd = FirebaseOptions(
    apiKey: 'AIzaSyAKYkwDTD1EGYgreG_hCmyWRXdG7GgFxMc',
    appId: '1:1036900576518:web:72b66c4c58bd8b4e9c0287',
    messagingSenderId: '1036900576518',
    projectId: 'hanko-field',
    authDomain: 'hanko-field.firebaseapp.com',
    storageBucket: 'hanko-field-prod.firebasestorage.app',
    measurementId: 'G-V2TDW9Z84Y',
  );
}
