name: hankofield
description: "STONE SIGNATURE - Custom Japanese seal design and ordering app."
publish_to: 'none'

version: 1.0.2+5

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter

  characters: ^1.4.0
  cupertino_icons: ^1.0.8
  google_fonts: ^6.3.2
  http: ^1.6.0
  url_launcher: ^6.3.2
  miniriverpod:
    path: ../../miniriverpod/miniriverpod
  declarative_nav:
    path: ../../declarative-nav/declarative_nav
  shared_preferences: ^2.5.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: Manrope
      fonts:
        - asset: assets/fonts/Manrope.ttf
    - family: Noto Serif JP
      fonts:
        - asset: assets/fonts/NotoSerifJP.ttf
    - family: Noto Serif
      fonts:
        - asset: assets/fonts/NotoSerif.ttf
  assets:
    - assets/site-logo.png
    - assets/top-hero.png
